## **Введение в библиотеку NumPy**
![Image](https://numpy.org/doc/stable/_static/numpy_logo.png)  
*NumPy* это библиотека Python для векторизованных вычислений. Написана на языке C.  
Читается как */ˈnʌmpaɪ/* (нам-пай).  
Главные преимущества NumPy перед стандартными функциями Python это большая **скорость** и меньшее количество используемой **памяти**.  

- [Официальный сайт](https://numpy.org/)  
    - [Быстрый старт](https://numpy.org/doc/stable/user/quickstart.html)
    - [Справочник](https://numpy.org/doc/stable/reference/index.html)    
- [GitHub](https://github.com/numpy/numpy)
- [Wikipedia](https://en.wikipedia.org/wiki/NumPy)
- [Курс "Введение в анализ данных" (2019)](https://www.youtube.com/playlist?list=PLrCZzMib1e9p6lpNv-yt6uvHGyBxQncEh)
- [100 задач NumPy](https://github.com/rougier/numpy-100)
- [Data Science Notebooks](https://github.com/donnemartin/data-science-ipython-notebooks)



---
### **Подключение библиотеки**

In [1]:
import numpy as np

np.__version__

'1.17.3'

In [2]:
a = list(range(1000000))

In [3]:
# %%timeit

# [element * element for element in a]

In [4]:
a = np.arange(1000000)

In [5]:
# %%timeit

# a * a

### **Создание массивов**

![image](https://numpy.org/doc/stable/_images/np_array.png)

In [6]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float64)

a

array([1., 2., 3., 4., 5.])

![Image](https://numpy.org/doc/stable/_images/np_create_matrix.png)

In [7]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [-1, -2, -3]
])

a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [-1, -2, -3]])

In [8]:
a.shape

(4, 3)

In [9]:
type(a.shape)

tuple

In [10]:
a.ndim

2

In [11]:
a.dtype

dtype('int64')

### **Типы данных**
Основные типы данных в NumPy:  
`np.int8`: Byte (-128 to 127)  
`np.int16`: Integer (-32768 to 32767)  
`np.int32`: Integer (-2147483648 to 2147483647)  
`np.int64`: Integer (-9223372036854775808 to 9223372036854775807)  

`np.uint8`: Unsigned integer (0 to 255)  
`np.uint16`: Unsigned integer (0 to 65535)  
`np.uint32`: Unsigned integer (0 to 4294967295)  
`np.uint64`: Unsigned integer (0 to 18446744073709551615)  

`np.float32`: Note that this matches the precision of the builtin python float  
`np.float64`: Note that this matches the precision of the builtin python float  

`np.complex64`: Complex number, represented by two 32-bit floats  
`np.complex128`: Note that this matches the precision of the builtin python complex  

[И другие...](https://numpy.org/doc/stable/user/basics.types.html#array-types-and-conversions-between-types)


In [12]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [-1, -2, -3]])

In [13]:
a.dtype

dtype('int64')

In [14]:
a.astype(np.complex128)

array([[ 1.+0.j,  2.+0.j,  3.+0.j],
       [ 4.+0.j,  5.+0.j,  6.+0.j],
       [ 7.+0.j,  8.+0.j,  9.+0.j],
       [-1.+0.j, -2.+0.j, -3.+0.j]])

### **Размерность массивов**
Массив в numpy хранится как единый последовательный набор данных. У этого набора есть характеристики:  
- `dtype` - тип данных
- `shape` - форма
- `strides` - количество байт для доступа к следующему элементу

![Image](https://miro.medium.com/max/1000/1*Ikn1J6siiiCSk4ivYUhdgw.png)

In [15]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [-1, -2, -3]])

In [16]:
a.dtype

dtype('int64')

In [17]:
a.dtype.itemsize

8

In [18]:
a.shape

(4, 3)

In [19]:
a.strides

(24, 8)

![Image](https://numpy.org/doc/stable/_images/np_reshape.png)

In [20]:
b = a.reshape(2, 6)

b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, -1, -2, -3]])

In [21]:
b.strides

(48, 8)

In [22]:
a.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, -1, -2, -3]])

### **Хранение массивов в памяти**
При присваивании массива другой переменной новый массив будет ссылаться на ту же область памяти, что и первоначальный.

In [23]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [-1, -2, -3]])

In [24]:
b = a.reshape(2, 6)

b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, -1, -2, -3]])

In [25]:
a[2, 1] = 100

In [26]:
a

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, 100,   9],
       [ -1,  -2,  -3]])

In [27]:
b

array([[  1,   2,   3,   4,   5,   6],
       [  7, 100,   9,  -1,  -2,  -3]])

Метод `flatten` "вытягивает" массив в одну линию и создает его полную копию.

In [28]:
b = a.flatten()
a[3, 2] = 111

a

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, 100,   9],
       [ -1,  -2, 111]])

In [29]:
b

array([  1,   2,   3,   4,   5,   6,   7, 100,   9,  -1,  -2,  -3])

Метод `ravel` "вытягивает" массив в одну линию, но полной копии не создает.

In [30]:
b = a.ravel()
a[3, 2] = 111

b

array([  1,   2,   3,   4,   5,   6,   7, 100,   9,  -1,  -2, 111])

Атрибут `T` транспонирует исходный массив, но полной копии не создает.
![Image](https://numpy.org/doc/stable/_images/np_transposing_reshaping.png)

Транспонирование матрицы A:  
$A = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}$

$A ^ \tau = \begin{bmatrix}
1 & 3 & 5\\
2 & 4 & 6
\end{bmatrix}$

In [31]:
a

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, 100,   9],
       [ -1,  -2, 111]])

In [32]:
c = a.T

c

array([[  1,   4,   7,  -1],
       [  2,   5, 100,  -2],
       [  3,   6,   9, 111]])

In [33]:
a[0, 0] = 222

c

array([[222,   4,   7,  -1],
       [  2,   5, 100,  -2],
       [  3,   6,   9, 111]])

### **Фиктивные оси (оси с размерностью 1)**
Используется для того, чтобы библиотека могла проводить операции над массивами с одинаковой размерностью.

In [34]:
a = np.arange(15)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
a.shape

(15,)

In [36]:
a.ndim

1

In [37]:
b = a[np.newaxis, :]

In [38]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [39]:
b.shape

(1, 15)

In [40]:
b.ndim

2

In [41]:
c = a[:, np.newaxis]

In [42]:
c

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [43]:
a[np.newaxis, np.newaxis, :]

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]])

In [44]:
a[np.newaxis, np.newaxis, :].shape

(1, 1, 15)

### **Создание особенных массивов**
![Image](https://numpy.org/doc/stable/_images/np_ones_zeros_matrix.png)

In [45]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [48]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [50]:
np.arange(25, 50, 5)

array([25, 30, 35, 40, 45])

In [51]:
np.arange(1, 15, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5])

In [52]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### **Генератор случайных чисел**

In [163]:
np.random.seed(12321)

In [164]:
np.random.rand(15)

array([0.18325525, 0.7969142 , 0.05063654, 0.08596682, 0.43223338,
       0.70304694, 0.43190833, 0.27597651, 0.58900897, 0.43063381,
       0.97426208, 0.72385849, 0.45790999, 0.09685338, 0.85620942])

In [140]:
np.random.randint(-9, 10, 15)

array([-5,  9,  8,  3, -3, -3, -7,  7, -7, -5, -8,  2, -1, -7,  8])

In [141]:
np.random.permutation(5)

array([0, 2, 3, 1, 4])

In [142]:
np.random.choice(4, size=20)

array([1, 2, 0, 2, 1, 0, 0, 3, 2, 2, 0, 2, 1, 3, 3, 2, 1, 1, 3, 3])

### **Создание массивов из существующих массивов**
Метод `array` создает новый массив, который занимает отдельную область памяти.  
Метод `asarray` создает новый массив, указывающий на ту же память, что и исходный массив.  

In [53]:
a = np.array(range(10))
b = np.array(a)
c = np.asarray(a)

a, b, c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [54]:
a[5] = 0

a, b, c

(array([0, 1, 2, 3, 4, 0, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 0, 6, 7, 8, 9]))

### **Поэлементные операции над массивами**
![Image](https://numpy.org/doc/stable/_images/np_multiply_broadcasting.png)

In [55]:
a = np.array(range(36)).reshape(6, 6)

a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [56]:
a + 2

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37]])

In [57]:
a - 2

array([[-2, -1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

In [58]:
a * 10

array([[  0,  10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100, 110],
       [120, 130, 140, 150, 160, 170],
       [180, 190, 200, 210, 220, 230],
       [240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350]])

In [59]:
a / 10

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. , 1.1],
       [1.2, 1.3, 1.4, 1.5, 1.6, 1.7],
       [1.8, 1.9, 2. , 2.1, 2.2, 2.3],
       [2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5]])

In [60]:
a ** 2

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [61]:
np.power(a, 2)

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [62]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
        8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08, 1.31881573e+09,
        3.58491285e+09, 9.74480345e+09],
       [2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
        1.44625706e+12, 3.93133430e+12],
       [1.06864746e+13, 2.90488497e+13, 7.89629602e+13, 2.14643580e+14,
        5.83461743e+14, 1.58601345e+15]])

In [63]:
np.cos(a)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
         0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
         0.0044257 ],
       [ 0.84385396,  0.90744678,  0.13673722, -0.75968791, -0.95765948,
        -0.27516334],
       [ 0.66031671,  0.98870462,  0.40808206, -0.54772926, -0.99996083,
        -0.53283302],
       [ 0.42417901,  0.99120281,  0.64691932, -0.29213881, -0.96260587,
        -0.74805753],
       [ 0.15425145,  0.91474236,  0.83422336, -0.01327675, -0.84857027,
        -0.90369221]])

In [64]:
a > 20

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

### **Вставка и удаление**

In [162]:
a = np.random.randint(10, size=5)

a

array([9, 4, 4, 0, 3])

In [66]:
a = np.insert(a, 3, 100)

In [67]:
a

array([  1,   7,   5, 100,   3,   0])

In [68]:
a = np.delete(a, 2)

In [69]:
a

array([  1,   7, 100,   3,   0])

### **Агрегирующие функции**

![Image](https://numpy.org/doc/stable/_images/np_aggregation.png)

In [70]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [-1, -2, -3]
])

a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [-1, -2, -3]])

In [71]:
#np.max(a)
a.max()

9

In [72]:
#np.min(a)
a.min()

-3

In [73]:
#np.sum(a)
a.sum()

39

In [74]:
#np.argmax(a)
a.argmax()

8

In [75]:
#np.prod(a)
a.prod()

-2177280

In [76]:
a = np.random.randint(-9, 10, size=(4, 8))

a

array([[-8,  6, -5,  2,  5, -9,  0, -7],
       [ 2, -7, -5,  8, -3,  0, -2,  9],
       [ 2, -1, -7,  9,  4,  4, -1,  9],
       [-9, -6, -2,  0,  4,  8,  1,  2]])

![Image](https://numpy.org/doc/stable/_images/np_matrix_aggregation_row.png)

In [77]:
a.max(axis=0)

array([ 2,  6, -2,  9,  5,  8,  1,  9])

In [78]:
a.max(axis=1)

array([6, 9, 9, 8])

### **Операции над булевыми массивами**

In [79]:
a = np.array([False, True, True, False, True])

a

array([False,  True,  True, False,  True])

In [80]:
#np.any(a)
a.any()

True

In [81]:
#np.all(a)
a.all()

False

In [82]:
a = np.array([
    [False, True, True, False, True],
    [True, True, False, False, True]
])

a

array([[False,  True,  True, False,  True],
       [ True,  True, False, False,  True]])

In [83]:
a.any(axis=0)

array([ True,  True,  True, False,  True])

In [84]:
a.all(axis=0)

array([False,  True, False, False,  True])

In [85]:
a.any(axis=1)

array([ True,  True])

In [86]:
a.all(axis=1)

array([False, False])

### **Бинарные операции**
![Image](https://numpy.org/doc/stable/_images/np_sub_mult_divide.png)

In [87]:
a = np.random.randint(-9, 10, size=(3, 4))

a

array([[-5,  2,  5,  4],
       [ 9, -8, -4, -1],
       [ 4, -8,  3,  9]])

In [88]:
b = np.random.randint(-9, 10, size=(3, 4))

b

array([[ 8,  2,  9, -3],
       [ 8,  3,  5,  7],
       [-2, -4, -8, -6]])

In [89]:
a + b

array([[  3,   4,  14,   1],
       [ 17,  -5,   1,   6],
       [  2, -12,  -5,   3]])

In [90]:
a * b

array([[-40,   4,  45, -12],
       [ 72, -24, -20,  -7],
       [ -8,  32, -24, -54]])

In [91]:
a > b

array([[False, False, False,  True],
       [ True, False, False, False],
       [ True, False,  True,  True]])

In [92]:
a == b

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### **Бинарные операции над булевыми массивами**

In [93]:
a = np.array([
    [False, True, True, False, True],
    [True, True, False, False, True]
])

a

array([[False,  True,  True, False,  True],
       [ True,  True, False, False,  True]])

In [94]:
b = np.array([
    [False, False, True, False, False],
    [True, False, False, True, True]
])

b

array([[False, False,  True, False, False],
       [ True, False, False,  True,  True]])

In [95]:
np.logical_not(a)

array([[ True, False, False,  True, False],
       [False, False,  True,  True, False]])

In [96]:
np.logical_and(a, b)

array([[False, False,  True, False, False],
       [ True, False, False, False,  True]])

In [97]:
np.logical_or(a, b)

array([[False,  True,  True, False,  True],
       [ True,  True, False,  True,  True]])

In [98]:
np.logical_xor(a, b)

array([[False,  True, False, False,  True],
       [False,  True, False,  True, False]])

### **Матричные операции**

In [99]:
a = np.arange(5, 17).reshape(3, 4)

a

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [100]:
b = np.arange(-5, 3).reshape(4, 2)

b

array([[-5, -4],
       [-3, -2],
       [-1,  0],
       [ 1,  2]])

In [101]:
# Ошибка!

# a * b

In [102]:
a.dot(b)

array([[ -42,  -16],
       [ -74,  -32],
       [-106,  -48]])

In [103]:
np.matmul(a, b)

array([[ -42,  -16],
       [ -74,  -32],
       [-106,  -48]])

In [104]:
# m1 = np.asmatrix(a)
m1 = np.matrix(a)

m1

matrix([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [105]:
# m2 = np.asmatrix(b)
m2 = np.matrix(b)

m2

matrix([[-5, -4],
        [-3, -2],
        [-1,  0],
        [ 1,  2]])

In [106]:
m1 * m2

matrix([[ -42,  -16],
        [ -74,  -32],
        [-106,  -48]])

In [107]:
m1.dot(m2)

matrix([[ -42,  -16],
        [ -74,  -32],
        [-106,  -48]])

In [108]:
np.matmul(m1, m2)

matrix([[ -42,  -16],
        [ -74,  -32],
        [-106,  -48]])

### **Срезы**

![Image](https://numpy.org/doc/stable/_images/np_indexing.png)

массив[*первый индекс* : *последний индекс* : *шаг*]

Если одно из этих значений пропущено, то вместо него принимается значение по умолчанию:  
- первый индекс = **0**
- последний индекс = **длина массива**
- шаг = **1**  


In [109]:
a = np.arange(15)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [110]:
a[0], a[4], a[len(a) - 2]

(0, 4, 13)

In [111]:
a[-1]

14

In [112]:
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [113]:
a[1::2]

array([ 1,  3,  5,  7,  9, 11, 13])

### **Использование логических масок**

In [114]:
a = np.random.randint(-9, 10, 15)

a

array([-5,  3,  2, -5, -1, -8, -3, -1, -6, -3,  1, -3, -7, -1,  4])

In [115]:
a > 3

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True])

In [116]:
a[a > 3]

array([4])

In [117]:
a % 2 == 0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False, False, False, False,  True])

In [118]:
a[a % 2 == 0]

array([ 2, -8, -6,  4])

In [119]:
a[np.logical_or(a % 2 == 0, a % 3 == 0)]

array([ 3,  2, -8, -3, -6, -3, -3,  4])

In [120]:
a[np.logical_and(a % 2 == 0, a % 3 == 0)]

array([-6])

### **Индексация в многомерных массивах**
![Image](https://numpy.org/doc/stable/_images/np_matrix_indexing.png)

In [121]:
a = np.random.randint(-9, 10, (5, 5))

a

array([[-9, -5,  6, -1, -4],
       [ 6, -1, -9, -2, -5],
       [ 9,  2,  2, -2,  3],
       [-7,  0,  3, -3, -1],
       [ 5,  6, -2, -3,  8]])

In [122]:
# Способ хорош для стандартный Python-списков, но не для NumPy-массивов

a[2][0]

9

In [123]:
a[2, 0]

9

In [124]:
a[3, :]

array([-7,  0,  3, -3, -1])

In [125]:
a[:, 2]

array([ 6, -9,  2,  3, -2])

In [126]:
a[:, ::2]

array([[-9,  6, -4],
       [ 6, -9, -5],
       [ 9,  2,  3],
       [-7,  3, -1],
       [ 5, -2,  8]])

In [127]:
a

array([[-9, -5,  6, -1, -4],
       [ 6, -1, -9, -2, -5],
       [ 9,  2,  2, -2,  3],
       [-7,  0,  3, -3, -1],
       [ 5,  6, -2, -3,  8]])

In [128]:
a < 0

array([[ True,  True, False,  True,  True],
       [False,  True,  True,  True,  True],
       [False, False, False,  True, False],
       [ True, False, False,  True,  True],
       [False, False,  True,  True, False]])

In [129]:
a[a < 0]

array([-9, -5, -1, -4, -1, -9, -2, -5, -2, -7, -3, -1, -2, -3])

In [130]:
np.where(a < 0)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 3, 3, 3, 4, 4]),
 array([0, 1, 3, 4, 1, 2, 3, 4, 3, 0, 3, 4, 2, 3]))

In [131]:
a[np.where(a < 0)]

array([-9, -5, -1, -4, -1, -9, -2, -5, -2, -7, -3, -1, -2, -3])

In [132]:
a

array([[-9, -5,  6, -1, -4],
       [ 6, -1, -9, -2, -5],
       [ 9,  2,  2, -2,  3],
       [-7,  0,  3, -3, -1],
       [ 5,  6, -2, -3,  8]])

In [133]:
a[[3, 4, 1]]

array([[-7,  0,  3, -3, -1],
       [ 5,  6, -2, -3,  8],
       [ 6, -1, -9, -2, -5]])

In [134]:
a[:, [2, 4, 0]]

array([[ 6, -4, -9],
       [-9, -5,  6],
       [ 2,  3,  9],
       [ 3, -1, -7],
       [-2,  8,  5]])

In [135]:
a = np.arange(24).reshape(2, 3, 4)

a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [136]:
a[..., 0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [137]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [138]:
a[..., 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

### **Сортировка массивов**

In [143]:
a = np.random.randint(-99, 100, size=(25, 4))

a

array([[ 86,  41,  42,  80],
       [ 39, -87, -97,  76],
       [ 17, -37,  81,  25],
       [-72,  10,  56, -23],
       [-81,  53,  11,  89],
       [-92, -26, -31,  35],
       [-51,  -5,  80, -99],
       [  2, -57, -62,  38],
       [-68, -47, -32,  84],
       [ 49,  92,  47, -21],
       [-93, -32, -13,  44],
       [-44,  37,  30,  96],
       [ 56,  92, -63,  14],
       [ 28, -48, -21,  65],
       [ 16,  38,  -7,  32],
       [-95, -22, -56,  28],
       [ -8, -17,  59, -34],
       [-11,  42, -66,   6],
       [ 12, -52,  -9,  53],
       [-82, -53, -44,  84],
       [-84, -65,   8, -46],
       [-56, -27,  16, -85],
       [-13,  99,  26, -74],
       [-26,  -4,  36, -70],
       [-27, -80, -96,  83]])

In [144]:
np.sort(a)

array([[ 41,  42,  80,  86],
       [-97, -87,  39,  76],
       [-37,  17,  25,  81],
       [-72, -23,  10,  56],
       [-81,  11,  53,  89],
       [-92, -31, -26,  35],
       [-99, -51,  -5,  80],
       [-62, -57,   2,  38],
       [-68, -47, -32,  84],
       [-21,  47,  49,  92],
       [-93, -32, -13,  44],
       [-44,  30,  37,  96],
       [-63,  14,  56,  92],
       [-48, -21,  28,  65],
       [ -7,  16,  32,  38],
       [-95, -56, -22,  28],
       [-34, -17,  -8,  59],
       [-66, -11,   6,  42],
       [-52,  -9,  12,  53],
       [-82, -53, -44,  84],
       [-84, -65, -46,   8],
       [-85, -56, -27,  16],
       [-74, -13,  26,  99],
       [-70, -26,  -4,  36],
       [-96, -80, -27,  83]])

In [145]:
# Возвращает копию

np.sort(a.ravel())

array([-99, -97, -96, -95, -93, -92, -87, -85, -84, -82, -81, -80, -74,
       -72, -70, -68, -66, -65, -63, -62, -57, -56, -56, -53, -52, -51,
       -48, -47, -46, -44, -44, -37, -34, -32, -32, -31, -27, -27, -26,
       -26, -23, -22, -21, -21, -17, -13, -13, -11,  -9,  -8,  -7,  -5,
        -4,   2,   6,   8,  10,  11,  12,  14,  16,  16,  17,  25,  26,
        28,  28,  30,  32,  35,  36,  37,  38,  38,  39,  41,  42,  42,
        44,  47,  49,  53,  53,  56,  56,  59,  65,  76,  80,  80,  81,
        83,  84,  84,  86,  89,  92,  92,  96,  99])

In [146]:
# Сортировка "на месте"

a.sort(axis=0)

a

array([[-95, -87, -97, -99],
       [-93, -80, -96, -85],
       [-92, -65, -66, -74],
       [-84, -57, -63, -70],
       [-82, -53, -62, -46],
       [-81, -52, -56, -34],
       [-72, -48, -44, -23],
       [-68, -47, -32, -21],
       [-56, -37, -31,   6],
       [-51, -32, -21,  14],
       [-44, -27, -13,  25],
       [-27, -26,  -9,  28],
       [-26, -22,  -7,  32],
       [-13, -17,   8,  35],
       [-11,  -5,  11,  38],
       [ -8,  -4,  16,  44],
       [  2,  10,  26,  53],
       [ 12,  37,  30,  65],
       [ 16,  38,  36,  76],
       [ 17,  41,  42,  80],
       [ 28,  42,  47,  83],
       [ 39,  53,  56,  84],
       [ 49,  92,  59,  84],
       [ 56,  92,  80,  89],
       [ 86,  99,  81,  96]])

In [147]:
a.sort(axis=1)

a

array([[-99, -97, -95, -87],
       [-96, -93, -85, -80],
       [-92, -74, -66, -65],
       [-84, -70, -63, -57],
       [-82, -62, -53, -46],
       [-81, -56, -52, -34],
       [-72, -48, -44, -23],
       [-68, -47, -32, -21],
       [-56, -37, -31,   6],
       [-51, -32, -21,  14],
       [-44, -27, -13,  25],
       [-27, -26,  -9,  28],
       [-26, -22,  -7,  32],
       [-17, -13,   8,  35],
       [-11,  -5,  11,  38],
       [ -8,  -4,  16,  44],
       [  2,  10,  26,  53],
       [ 12,  30,  37,  65],
       [ 16,  36,  38,  76],
       [ 17,  41,  42,  80],
       [ 28,  42,  47,  83],
       [ 39,  53,  56,  84],
       [ 49,  59,  84,  92],
       [ 56,  80,  89,  92],
       [ 81,  86,  96,  99]])

### **Уникальные элементы**

In [148]:
a = np.random.randint(10, size=15)

a

array([6, 7, 6, 8, 4, 3, 8, 2, 9, 9, 7, 3, 9, 3, 6])

In [149]:
a.size

15

In [150]:
np.unique(a)

array([2, 3, 4, 6, 7, 8, 9])

In [151]:
np.unique(a).size

7

### **Объединение массивов**

In [152]:
a = np.random.randint(10, size=(3, 4))
b = np.random.randint(10, size=(3, 4))

In [153]:
a

array([[9, 2, 1, 2],
       [6, 4, 1, 5],
       [5, 6, 0, 1]])

In [154]:
b

array([[4, 1, 5, 4],
       [8, 9, 2, 4],
       [3, 3, 6, 8]])

In [155]:
np.vstack((a, b))

array([[9, 2, 1, 2],
       [6, 4, 1, 5],
       [5, 6, 0, 1],
       [4, 1, 5, 4],
       [8, 9, 2, 4],
       [3, 3, 6, 8]])

In [156]:
np.concatenate((a, b), axis=0)

array([[9, 2, 1, 2],
       [6, 4, 1, 5],
       [5, 6, 0, 1],
       [4, 1, 5, 4],
       [8, 9, 2, 4],
       [3, 3, 6, 8]])

In [157]:
np.hstack((a, b))

array([[9, 2, 1, 2, 4, 1, 5, 4],
       [6, 4, 1, 5, 8, 9, 2, 4],
       [5, 6, 0, 1, 3, 3, 6, 8]])

In [158]:
np.concatenate((a, b), axis=1)

array([[9, 2, 1, 2, 4, 1, 5, 4],
       [6, 4, 1, 5, 8, 9, 2, 4],
       [5, 6, 0, 1, 3, 3, 6, 8]])

### **Разбиение массива**

In [159]:
a = np.random.randint(10, size=(5, 4))

a

array([[2, 0, 0, 5],
       [7, 1, 8, 0],
       [0, 4, 4, 5],
       [1, 1, 2, 6],
       [0, 3, 4, 3]])

In [160]:
np.vsplit(a, 5)

[array([[2, 0, 0, 5]]),
 array([[7, 1, 8, 0]]),
 array([[0, 4, 4, 5]]),
 array([[1, 1, 2, 6]]),
 array([[0, 3, 4, 3]])]

In [2]:
np.hsplit(a, 4)

NameError: name 'np' is not defined